### PR TITLE
Added new rules

### PR DESCRIPTION
**Pull request by 31vi5**

### CODE REVIEW

**Comment by paveljanda** [comment]
What means `IncorrectLinesCountBeforeControlStructure`? Otherwise I am OK with it.

**Comment by 31vi5** [comment]
Forces
```
$i = 0;

foreach ($array as $item) {
	$i++;
}
```
instead of this

```
$i = 0;
foreach ($array as $item) {
	$i++;
}
```

**Comment by paveljanda** [comment]
I personally prefer the first (forced) version and would like to keep that rule. Which version of previously mentioned code do you use? @bhaal-nig

**Comment by bhaal-nig** [comment]
In this case I prefer second option, when the $i is not used in foreach i prefer first option

**Comment by paveljanda** [comment]
Ok, let's merge this MR then.

**Pull request merged**
